<?php include("initialize.php"); ?>

<div class="Verdana size16" style="margin: 10px 35px; line-height: 22px;">

 <span class="darkred size24 Tahoma"><b>AFFILIATE OPPORTUNITY EXPLAINED</b></span>

<p style="margin-top: 30px;">Not only can PUSHY! generate an avalanche of targeted traffic to your website, but he loves to reward members for referring others to Get PUSHY! In fact, one of his built-in viral components (soon to be on millions of web pages) will redirect prospects to YOUR affiliate page, where they will anxiously stand in line to make you money, hand over fist (<i>more details on this viral component inside your member backoffice</i>).

<p>We're not talking about chicken feed here either. He splits everything right off the top, right down the middle, then pays for all the expenses incurred by PushyAds.com out of his own pocket. In other words, your gross earnings are based on half of the gross revenues generated by your referrals (<i>see Compensation Plan inside your member backoffice for details</i>).

<p>And the beauty of it all is this. Because he is the King of Conversions (really, I'm serious), trained in gorilla marketing warfare (he ain't no pushover), and uses all 7 viral marketing techniques like a wild ninja fighting machine, his PUSHY Technology virtually does all the work for you.

<div align=center class="bold darkred Verdana size18" style="margin:30px"><a href="javascript:newmemberSignUp()">What are you waiting for? Go Sign Up! It's FREE</a></div>

<p>Just like always, when people get wind of new technology, and learn there is big money to be made, a stampede of opportunists & big dogs come out of the woodwork. Those who get in early, stand to make fortunes.

<p>But PUSHY isn't one who likes to brag about everything he can do, nor how much money he's going to make you. Heck, he has no control over whether or not you sit on your thumbs, or how little or how much you do, or don't do. All he can tell you is that he's giving away the lion's share of the profits to his affiliates, JV partners, and every Tom, Dick, and Harry who wants to jump on what could be the biggest opportunity to hit the decade.

<p>On top of that, he'll give you
  <ul>
    <li>A replicated website (just like the one you're looking at)
    <li>Automated ordering system (works while you sleep)
    <li>Professional ad copy (that makes it irresistible for most people to Sign Up)
    <li>High converting, attention grabbing banner ads
    <li>Compelling Email teasers
    <li>Taglines, Twitter messages, 
    <li>Social Network tools
    <li>Backoffice exposure to other PUSHY members
    <li>Extensive Analytic & Traffic Reports 
    <li>Video training
    <li>Support desk
    <li>Professional follow up messages to all your prospects & referrals
    <li>Special ad placement options in the PUSHY Network
    <li>PUSHY Technology to generate targeted traffic for even more referrals
  </ul>

<div align=center class="bold darkred Verdana size18" style="margin:30px"><a href="javascript:newmemberSignUp()">Enough already! Sign Me Up! After all, It's FREE</a></div>

<p>Everything is explained in detail, as soon as you signup. There is a special message waiting for you from the Founder and co-creator of PUSHY!, who will hold you by the hand to get you started within minutes from now. Go ahead! Click on the button below, and let's get started Now!


<p align=center style="margin: 20px 0 35px;"><a href="javascript:newmemberSignUp()"><img src="http://pds1106.s3.amazonaws.com/images/sign-up-y.png"></a></p>

</div>
